# example values

indexing-settings:
  sites:
#    - url: https://www.skillbox.ru
#      name: Skillbox

#    - url: https://www.culture.ru/literature/poems/author-vladimir-mayakovskii
#      name: Маяковский

    - url: https://markulmusic.com/
      name: Markul
server:
  port: 8080

spring:
  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost:3306/searchengine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
